---

image: docker.harrigan.online/clojure/docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  GITLIBS: ".gitlibs"

# I don't think this cache thing works..., so I've disabled it for now.
.cache:
  before_script:
    - sed -i 's,;;CI ,,g' deps.edn
  cache:
    key:
      files:
        - deps.edn
    paths:
      - .cpcache
      - .gitlibs
      - .m2/repository

stages:
  - package
  - publish

services:
  - name: docker:dind
    command: ["--registry-mirror", "https://docker.harrigan.online"]

package:
  #extends: .cache
  stage: package
  script:
    - just build
  artifacts:
    paths:
      - target/app.jar
    expire_in: 1 day

publish:
  stage: publish
  dependencies:
    - package
  variables:
    DOCKER_CONFIG: /root/.docker
  before_script:
    - mkdir -p $DOCKER_CONFIG
    - echo "$DOCKER_AUTH_CONFIG" > $DOCKER_CONFIG/config.json
  script:
    - just imagify publish
  only:
    - master
  except:
    - branches
  tags:
    - docker
