---

services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:latest
    ports:
      - 6379:6379
